definitions: {}
info: {title: A safe Random swagger Petstore, version: 1.0.0}
parameters: {}
paths:
  /random/{kind}:
    post:
      description: POST a pet
      parameters:
      - {description: Path Parameter description in Markdown., in: path, name: kind,
        required: true, type: string}
      responses:
        200: {description: Pet POSTed successfully}
        400:
          description: Global fail
          schema: {example: something global went wrong, type: string}
    get:
      consumes: [application/json, application/xml, application/xml+dec1]
      description: Get a pet
      parameters:
      - {description: Path Parameter description in Markdown., in: path, name: kind,
        required: true, type: string}
      - {description: Query Parameter description in Markdown., in: query, name: offset,
        type: string}
      produces: [application/json, application/xml]
      responses:
        200:
          description: A pet to be returned
          schema: {example: fido, type: string}
        400:
          description: Something went wrong
          schema: {example: something global went wrong, type: string}
        402:
          description: mefail
          schema: {example: decorate2 error, type: string}
      security:
      - ApiKeyAuth: []
      - AlmostBasicAuth: []
        BasicAuth: []
      - OAuth2: [scope1, scope2]
      tags: [down1, up1, get2]
  /random2/{kind}:
    post:
      description: POST a pet
      parameters:
      - {description: Path Parameter description in Markdown., in: path, name: kind,
        required: true, type: string}
      responses:
        200: {description: Pet POSTed successfully}
    get:
      consumes: [application/json, application/xml]
      description: Get a pet
      parameters:
      - {description: Path Parameter description in Markdown., in: path, name: kind,
        required: true, type: string}
      - {description: Query Parameter description in Markdown., in: query, name: offset,
        type: string}
      produces: [application/json, application/xml]
      responses:
        200:
          description: A pet to be returned
          schema: {example: fido, type: string}
      security:
      - ApiKeyAuth: []
responses: {}
securityDefinitions: {}
swagger: '2.0'
tags: []

